### ISSUE TITLE
Problem with touch command ("Reading a .txt file")

### ISSUE THREAD

**Issue by clairefio** [NCAR/python-tutorial#12]
In step 14 when I tried to execute 'touch mysci.py' I received the error "'touch' is not recognized as an internal or external command". I needed to do a "conda install m2-base" to be able to use unix commands such as touch in my anaconda terminal.

**Comment by kmpaul** [comment]
@clairefio!  Thanks for both the bug report *and* the suggested fix!  This is fantastic!
