### ISSUE TITLE
Using a Text Editor ("Reading a .txt file")

### ISSUE THREAD

**Issue by clairefio** [NCAR/python-tutorial#13]
In step 15, I was unable to access a text editor such as vim or nano within my anaconda terminal. On my machine, the easiest way to access my file was using command "mysci.py", which opened a notepad window where I could edit the script.

**Comment by kmpaul** [comment]
Interesting.  Thanks, again, @clairefio!  Just to clarify, what was the actual command that you executed on your Windows machine in the Anaconda Prompt?  Did you just execute: `mysci.py`?

**Comment by clairefio** [comment]
> Interesting. Thanks, again, @clairefio! Just to clarify, what was the actual command that you executed on your Windows machine in the Anaconda Prompt? Did you just execute: `mysci.py`?

Yes, 'mysci.py' was the full command.
