### ISSUE TITLE
Specifying which terminal to open ("Reading a .txt file")

### ISSUE THREAD

**Issue by clairefio** [NCAR/python-tutorial#14]
Maybe it would be good to specify which terminal to open up in the first section of the tutorial. I assumed it was an anaconda/miniconda terminal, but some computers also have a regular terminal, powershell terminal, bash terminal, etc.

**Comment by kmpaul** [comment]
Yes.  We need to be clear about this.  Thanks for the catch!

**Comment by jukent** [comment]
@kmpaul What should we say? A regular terminal or an anaconda terminal will both work, correct?

**Comment by kmpaul** [comment]
On Windows, we should say they should use **Anaconda Prompt**, not a regular terminal.  On Mac or Linux, a regular terminal should be fine.
