### ISSUE TITLE
Why another Python tutorial?

### ISSUE THREAD

**Issue by jukent** [NCAR/python-tutorial#16]
I'm creating this issue to be the discussion place on the motivation behind this tutorial.

This is what I've written so far:

Why *this* Python tutorial?

What makes this Python tutorial unique is that is has been designed specifically to meet the needs of, and feedback from, atmospheric and oceanic scientists making the transition with the NCAR-wide [pivot-to-Python](https://www.ncl.ucar.edu/Document/Pivot_to_Python/). By spending the first day on pure Python without importing any additional packages, our beginner tutorial addresses the concerns that most tutorials pick up speed too quickly. By using coding examples with real atmospheric datasets and questions, the skills and techniques taught are easily applied to actual workflows. Intermediate and advanced tutorials were developed by working closely with scientists to transform their old code into Python using the most up-to-date tools for advanced computing. We hope that this tailored approach to teaching and sharing computational tools effectively addresses the concerns and needs of the geoscience community.

**Comment by jukent** [comment]
@kmpaul

**Comment by kmpaul** [comment]
I like this @jukent.  I have a few suggestions (in **bold**):

> Why _this_ Python tutorial?
> 
> What makes this Python tutorial unique is that is has been designed specifically to meet the needs of, and feedback from, atmospheric and oceanic scientists making the transition with the NCAR-wide [pivot-to-Python](https://www.ncl.ucar.edu/Document/Pivot_to_Python/). **In particular, this tutorial should be useful for *any* scientist who already knows how to program in some other language but is taking up Python for the first time.**  By spending the first day on pure Python without importing any additional packages, our beginner tutorial addresses the concerns that most tutorials **either** pick up speed too quickly **by going into the intricacies of third-party packages before explaining how Python is different from other languages, or get too bogged down in basic programming concepts that anyone with programming experience already knows.  This tutorial attempts to hit the sweet spot between too high-level and too low-level.** By using coding examples with real atmospheric datasets and questions, the skills and techniques taught are easily applied to actual **atmospheric or oceanic** workflows. **The intermediate** and advanced tutorials were developed by working closely with scientists to transform their old code into Python using the most up-to-date tools for advanced computing. We hope that this tailored approach to teaching and sharing computational tools effectively addresses the concerns and needs of the geoscience community.

**Comment by jukent** [comment]
Great edits!

I think I will put this on the home page as it addresses beginner and above tutorials.
