### ISSUE TITLE
Fix wording in "Interpreted languages" section

### ISSUE THREAD

**Issue by hCraker** [NCAR/python-tutorial#19]
For clarity, I don't believe you need the word "than" in this statement. Either that or finish the comparison by shifting some words around like this: "Sometimes [interpreted languages] can be slower and potentially more memory intensive than compiled languages."
![image](https://user-images.githubusercontent.com/42781301/84936984-1b2b3700-b0a9-11ea-9a6f-13a4f1b6fba2.png)

**Comment by jukent** [comment]
Good catch
