### ISSUE TITLE
Warning thrown after git add mysci.py

### ISSUE THREAD

**Issue by hCraker** [NCAR/python-tutorial#21]
Everytime after the first commit, this warning is thrown `warning: LF will be replaced by CRLF in mysci.py.
The file will have its original line endings in your working directory`

I'm not sure why this is happening, but what can we do to address it by either removing it or making a note in the tutorial?

**Comment by mnlevy1981** [comment]
@hCraker I think this is related to how windows and linux handle end-of-line differently (here's an [overview](https://stackoverflow.com/questions/419291/historical-reason-behind-different-line-ending-at-different-platforms) from stackoverflow); I can't vouch for [this](https://stackoverflow.com/a/17628353), but could you try

```
git config --global core.autocrlf false
```

If that avoids the warning, we could add that to the windows instructions.

**Comment by jukent** [comment]
@mnlevy1981 I had just added that!
