### ISSUE TITLE
GitHub instruction clarification

### ISSUE THREAD

**Issue by sherimickelson** [NCAR/python-tutorial#37]
In step number 10, "Let's push to GitHub!", I'm not sure if step number 6 needs more clarification.
If someone isn't familiar with GitHub, I'm not sure if they'll know what \<remote repository URL\> should be in the command

> git remote add origin \<remote repository URL\>

In step 5 you list 

> https://github.com/<user_name>/\<repo\>.git

Maybe make a note using something similar?

**Comment by jukent** [comment]
Good idea Sheri! I will add a note on this.
