### ISSUE TITLE
Add publishing your package to site

### ISSUE THREAD

**Issue by jukent** [NCAR/python-tutorial#58]
The "Your First Package" content is missing a final piece that ties the project up nicely where we push our work up to GitHub one last time and publish it.

**Comment by kmpaul** [comment]
@jukent:  Is this taken care of now?

**Comment by jukent** [comment]
Yes sorry. Forgot to have this issue closed by that PR. I will be doing a quick PR today with some of the changes we picked up on during the practice session.
