### ISSUE TITLE
Consistent argument names in compute_* functions

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/python-tutorial#67]
When we define `compute_heatindex()` the arguments are `t` and `hum`, but in `compute_dewpoint()` we represent the same values (temperature and humidity) as `t` and `h`; I think we want to use `hum` instead of `h` for consistency.

**Comment by zmoon** [comment]
I think `rh` for relative humidity would be better than `hum`/`h`. Or `rh_pct` or somesuch to emphasize that it should be in percentage form.

**Comment by jukent** [comment]
Good points! I will work on this next week.
